#Author:Matthew McGilvery
#!/bin/bash
tmux -2 new -s ntrm;
echo starting ntrm;
cd ~/nmbl;
alias shcp='cd ; cp .bashrc ~/nmbl/nsh/nbash.txt';
alias ntrcy='termux-open --send';
alias ccmp3='cloudconvert -f mp3';
alias ccwav='cloudconvert -f wav';
alias ccpng='cloudconvert -f png';
alias send='termux-open --send';
alias open='termux-open';
alias list='ls -lth';
alias apps='pkg list-installed';
alias hm='cd ~/nmbl';
alias bashed='cd && micro .bashrc';
alias gbrnch='cd ~/nmbl && git branch -l';
alias bcon='cd ~ && pwd && micro .bashrc';
alias rmd='rmdir --ignore-fail-on-non-empty';
alias ngit='bash ~/nmbl/nsh/n_git.sh';
alias nctrnm='cd ~/nmbl && pwd';
alias home='cd ~/nmbl && pwd';
alias gthb='lynx https://github.com/lssradm/nmbl';
alias google='lynx https://www.google.com/search?q='; 
alias sh101='man sh';
alias bash101='man bash';
alias png='echo ping && date && arp && httping -c 8 1.1.1.1 && arp -v -a -i wlan0';
alias png2='ping -c 8 -b google.com > ~/nmbl/nsudo/npng.txt'
alias pkgi='pkg install';
alias npmi='npm -g install';
alias apti='apt install';
alias ndcc='ccrypt -d';
alias ncc='ccrypt -e';
alias nroot='cd . && pwd';
alias note='micro';
alias nt='micro';
alias gitl='git log > ~/nmbl/nsudo/ngitl.txt';
alias google='lynx https://google.com/search';
alias fm='ranger ~/nmbl';
alias rngr='ranger ~/nmbl';
alias hm='mc ~/nmbl';
alias gitp='git push nmbl master';
alias tab='tmux new -c ntrm';
alias gitc='git commit -m "an update local nmbl repository"';
echo termial initalized;
echo network data;
echo user;
whoami > ~/nmbl/nsudo/nwhoami.txt;
echo wlan data;
ifconfig wlan0 > ~/nmbl/nsudo/nifconfig.txt;
echo host information;
arp > ~/nmbl/nsudo/narp.txt;
echo syncronising git branches;
git pull nmbl master;
git add --all;
git push nmbl master;
git commit -m  "syncing local git changes";
alias bed='cd && micro .bashrc';
#License: LGPL3
