#Matthew McGilvery
#Bash Inistialization Script
#code.nctrnm.com
#!/bin/bash/
#7.20.2020
#Bash Initialization File
termux-chroot
stty rows $((2800/900))  && stty columns $((7100/500))
export set USER='nctrnm'
export set PS1='$(pwd): '
alias g='cd'
alias github='termux-open https://github.com/nctrnm'
alias kf='termux-open https://tunebat.com/Analyzer'
alias nex='bash wip/sh/nexif.sh'
alias wip='cd /storage/emulated/0/wip'
alias doc='cd /storage/emulated/0/wip/doc/'
alias img='cd /storage/emulated/0/wip/img'
alias sound='cd /storage/emulated/0/wip/sound'
alias sxh='sox --help-effect'
alias nsig='pgrep -u u0_a224' && alias x='kill -9 $(nsig|fmt -n u/)'
alias sx='sox -SV -r44.1k -b16 -c1'
alias chr='termux-chroot'
alias copi='termux-clipboard-set' && alias pst='termux-clipboard-get'
alias py='python3.8'
alias pl='play'
alias freespc='cd /storage/emulated/0/ && rm -rvf $(du -xt 500000|grep "cache"|fmt -u)'
alias googlr='tmux lynx encrypted.google.com/'
alias p='mpv'
alias google='lynx https://google.com/search?q='
alias cop='termux-clipboard-set'
alias usr='echo $USER'
alias o='termux-open' && alias n.h='cd /storage/emulated/0/ && pwd'
alias ls='exa' && alias list='exa -l'
alias snd='termux-open --send'
alias srch='pkg search'
alias shcp='cp ~/.bashrc /storage/emulated/0/nctrnmCODE/n.bashrc.android.sh'
alias sgit='git status' && alias p.git='git push'
alias lsx='exa -bhtx' && alias apps='exa -bad /bin'
alias start='source ~/.bashrc'
alias shed='vim ~/.bashrc ; cp ~/.bashrc /storage/emulated/0/nctrnmCODE/n.bashrc.android.sh'
alias dd='rm -rf'
alias rec='termux-microphone-record -l 0 -f /storage/emulated/0/rec.tmux/n.${RANDOM}.wav  -r 44100  -b 16'
alias ngt='bash /storage/emulated/0/nctrnmCODE/sh/git_sync.sh'
alias rm.cache='rm -r $(bash /storage/emulated/0/nctrnmCODE/sh/n.cache.sh)'
alias gthb='lynx https://github.com/mwmcgilvery'
alias google='lynx https://www.google.com/search?q= ' 
alias i='pkg install'
alias u='pkg upgrade && npm update -g npm'
alias d='ccrypt -d'
alias c='ccrypt -e'
alias yx='/bin/play'
alias coned="cd  /data/data/com.termux/files/usr/etc/"
alias ncac='bash /storage/emulated/0/nctrnmCODE/sh/n.cache.sh'
alias recq='termux-microphone-record -q'
alias nt='vim'
alias ggl="lynx https://google.com/search?q=-"
alias pgit='git push'
alias ntab='tmux new -c ntm'
alias fm='nnn'
cd /storage/emulated/0/ &&  pwd && exa -bh .
