tmux new -s ntrm;
echo 'Logging into sdcard';
cd /storage/emulated/0/ngt;
pwd;
ping -b -c 8 google.com > /storage/emulated/0/ngt/nsudo/npng.txt;
echo logging global aliases;
alias bashed='cd ; micro .bashrc';
alias o='termux-open';
alias and='&&';
alias soxn='sox -b16 -r44100 /storage/emulated/0/ngt/nsox';
alias cnvrt='ffmpeg -i';
alias send='termux-open --send';
alias nbin='~/usr/bin';
alias search='apt search';
alias npngb='ping -b -c 8 127.0.0.1 > /storage/emulated/0/ngt/nsudo/npngb.txt; nt /storage/emulated/0/ngt/nsudo/npngb.txt';
alias nbin='cd /storage/emulated/0/ngt/nbin/';
alias shcp='cd ; cp .bashrc /storage/emulated/0/ngt/nsh/nbashrc.sh';
alias bincp='cd /data/data/com.termux/files/usr/bin/ && cp -r * /storage/emulated/0/ngt/nbin';
alias nmbl='/storage/emulated/0/ngt';
alias gits='git status';
alias send='termux-open --send';
alias open='termux-open';
alias list='ls -lth';
alias apps='pkg list-installed';
alias hm='/storage/emulated/0/ngt && pwd';
alias xtmux='tmux kill-session -t ntrm && exit';
alias bashed='cd && micro .bashrc && cp .bashrc /storage/emulated/0/ngt/nsh/nbashrc.sh';
alias gbrn='cd /storage/emulated/0/ngt && git branch -l;'
alias bcon='cd ~ && pwd && micro .bashrc';
alias ddir='rmdir --ignore-fail-on-non-empty';
alias ngit='bash /storage/emulated/0/ngt/nsh/n_git.sh';
alias nctrnm='cd /storage/emulated/0/ngt && pwd';
alias home='/storage/emulated/0/ngt';
alias gthb='lynx https://github.com/mwmcgilvery';
alias google='lynx https://www.google.com/search?q='; 
alias sh101='man sh';
alias bash101='man bash';
alias png='echo ping && date && arp && httping -c 8 1.1.1.1 && arp -v -a -i wlan0';
alias png2='ping -c 8 google.com > /storage/emulated/0/ngt/nsudo/npng.txt'
alias pkgi='pkg install';
alias ndcc='ccrypt -d';
alias ncc='ccrypt -e';
alias end='kill -9';
alias rt='cd . && pwd';
alias note='micro';
alias nt='micro';
alias gitl='git log > /storage/emulated/0/ngt/nsudo/ngitl.txt';
alias google='lynx https://google.com/search';
alias fm='ranger /storage/emulated/0/ngt';
alias rngr='ranger /storage/emulated/0/ngt';
alias hm='mc /storage/emulated/0/ngt';
alias gitp='git push nmbl';
alias gitl='git log';
alias tab='tmux new -c ntm';
alias gitc='git commit -m "updating mobile nmbl repository"';
alias nt='micro';
alias go='cd ';
alias fm='ranger';
alias x='kill job -1';
alias h='/storage/emulated/0/ngt';
alias p='ping ';
alias pg='ping -b -c 8 nctrnm.com > /storage/emulated/0/ngt/nsitepng.txt; micro /storage/emulated/0/nsitepng.txt';
echo 'Printing Global Aliases';
alias -p;
echo 'Saving Initialization File Updates';
cd ; cp .bashrc /storage/emulated/0/ngt/nsh/nbashrc.sh;
apt upgrade && pkg upgrade;                                  
echo preparing user info;                                    
whoami > /storage/emulated/0/ngt/nsudo/nwhoami.txt;
echo gathering wlan data;
ifconfig wlan0 > /storage/emulated/0/ngt/nsudo/nifconfig.txt;
echo gathering internet host information;
arp > /storage/emulated/0/ngt/nsudo/narp.txt;
echo syncronising nmbl git;
cd /storage/emulated/0/ngt && bash /storage/emulated/0/ngt/nsh/n_git.sh;
echo logging back into home directory;
cd /storage/emulated/0/ngt;
pwd;
echo 'Ready';
