echo "Logging into sdcard";
cd /sdcard/ngt;
echo "Setting Environmental variables";
declare -x HOME="/data/data/com.termux/files/home"
declare -x HOME2="/sdcard";
echo "printing environmental variables";
export -p;
pwd;
ping -b -c 8 google.com > /sdcard/ngt/nsudo/npng.txt;
echo logging global aliases;
alias bashed='cd ; micro .bashrc';
alias pgen='pwgen -1 -c -n -y';
alias o='termux-open';
alias nm='/sdcard/'FLM User Files'/'My Samples'/NctrnmSounds/';
alias and='&&';
alias soxn='sox -r44100 -b16 -c1';
alias cnvrn='ffmpeg -i';
alias send='termux-open --send';
alias instl='apt install';
alias nbn='~/usr/bin';
alias search='apt search';
alias npngb='ping -b -c 8 127.0.0.1 > /sdcard/ngt/nsudo/npngb.txt; nt /sdcard/ngt/nsudo/npngb.txt';
alias shcp='cd ; cp .bashrc /sdcard/ngt/nsh/nbashrc.sh';
alias bincp='cd /data/data/com.termux/files/usr/bin/ && cp -r * /sdcard/ngt/nbin';
alias nmbl='/sdcard/ngt';
alias gits='git status';
alias send='termux-open --send';
alias open='termux-open';
alias list='ls -lth';
alias apps='pkg list-installed';
alias hm='cd /sdcard/ngt && pwd';
alias xtmux='tmux kill-session -t ntrm && exit';
alias bashed='cd && micro .bashrc && cp .bashrc /sdcard/ngt/nsh/nbashrc.sh';
alias gbrn='cd /sdcard/ngt && git branch -l;'
alias ddir='rmdir --ignore-fail-on-non-empty';
alias ngit='bash /sdcard/ngt/nsh/n_git.sh';
alias nctrnm='cd /sdcard/ngt && pwd';
alias home='/sdcard/ngt';
alias gthb='lynx https://github.com/mwmcgilvery';
alias google='lynx https://www.google.com/search?q='; 
alias sh101='man sh';
alias bash101='man bash';
alias png='echo ping && date && arp && httping -c 8 1.1.1.1 && arp -v -a -i wlan0';
alias png2='ping -b -c8 https://google.com > /sdcard/ngt/nsudo/npng.txt && nt /sdcard/ngt/nsudo/npng.txt';
alias pkgi='pkg install';
alias ndcc='ccrypt -d';
alias ncc='ccrypt -e';
alias end='kill -9';
alias rt='cd . && pwd';
alias note='micro';
alias nt='micro';
alias gitl='git log > /sdcard/ngt/nsudo/ngitl.txt';
alias google='lynx https://google.com/search';
alias fmh='nnn /sdcard/ngt';
alias hm='mc /sdcard/ngt';
alias gitp='git push nmbl';
alias gitl='git log';
alias tab='tmux new -c ntm';
alias gitc='git commit -m "updating mobile nmbl repository"';
alias nt='micro';
alias go='cd ';
alias fm='nnn';
alias x='kill job -1';
alias h='/sdcard/ngt';
alias p='ping ';
alias flm='cd /sdcard/'FLM User Files'/'My Samples'/NctrnmSounds;
alias pg='ping -c8 nctrnm.com > /sdcard/ngt/nsitepng.txt; micro /sdcard/ngt/nsudo/nsitepng.txt';
echo Saving Initialization File Updates;
cd ; cp .bashrc /sdcard/ngt/nsh/nbashrc.sh;
echo Tidying Apps
apt upgrade &! npm -g update npm && pkg upgrade;                                  
echo "logging back into home directory";
cd /sdcard/;
pwd;
echo "Printing Global Aliases";
alias -p;
echo "Ready";

