#Matthew McGilvery
#4/28/2023
#Interactive Chat with OpenAI's GPT-4 Model using Python


import os

# Import the `openai` module. This module provides functions for interacting with the OpenAI API.
import openai

# Set the OpenAI API key. This key is required to use the OpenAI API (https://platform.openai.com/account/api-keys).
openai.api_key = os.environ["OPENAI_API_KEY"]

# Start a loop. This loop will continue to run until the user enters the word "quit".
while True:

  # Get the user's input.
  user_input = input("What would you like to ask me?\n")

  # Create a chatbot response. This response is generated by the OpenAI API.
  completion = openai.ChatCompletion.create(
    model="gpt-4",
    messages=[
      {"role": "user", "content": user_input}
    ]
  )
# Print the text of the chatbot response.
  print(completion)
  # Check if the user entered the word "quit".
  if user_input == "quit":
    break
