#!/data/data/com.termux/files/usr/bin/sh
#
# Configure options script for re-calling GraphicsMagick compilation
# options required to use the GraphicsMagick library.
#
# Concept derived from gtk-config in the Gtk package except that Autoconf-style
# configuration information is presented instead so that it may be used more
# effectively in configure scripts.
#
usage='Usage: GraphicsMagick-config [--cflags] [--cppflags] [--exec-prefix] [--ldflags] [--libs] [--prefix] [--version]

 For example, "example.c" may be compiled to produce "example" as follows:

  "gcc -o example example.c `GraphicsMagick-config --cppflags --cflags --ldflags --libs`"'

if test $# -eq 0; then
      echo "${usage}" 1>&2
      exit 1
fi

while test $# -gt 0; do
  case $1 in
    --prefix)
      echo /data/data/com.termux/files/usr
      ;;
    --exec-prefix)
      echo /data/data/com.termux/files/usr
      ;;
    --version)
      echo 1.3.33
      ;;
    --cflags)
      echo '-fopenmp -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -Oz -Wall'
      ;;
    --cppflags)
      echo '-I/data/data/com.termux/files/usr/include/GraphicsMagick'
      ;;
    --ldflags)
      echo '-L/data/data/com.termux/files/usr/lib -L/data/data/com.termux/files/usr/lib -march=armv7-a -Wl,-rpath=/data/data/com.termux/files/usr/lib,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -L/data/data/com.termux/files/usr/lib'
      ;;
    --libs)
      echo '-lGraphicsMagick -llcms2 -ltiff -lfreetype -ljasper -ljpeg -lpng16 -llzma -lbz2 -lxml2 -lz -lzstd -lm -lomp'
      ;;
    *)
      echo "${usage}" 1>&2
      exit 1
      ;;
  esac
  shift
done

